"use client";
import {useEffect,useRef,useState} from "react";
import {Hash,Plus,Copy,Search,RotateCw,ShieldCheck,ClipboardList,Settings,Users} from "lucide-react";
import {Toaster} from "@/components/ui/sonner";
import {toast} from "sonner";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from "@/components/ui/alert-dialog";
type Order={seq:number;ordinal:number;code:string;customer:string;memo:string;amount:number|null;created_at:string;cancelled_at:string|null};
type Staff={code:string;name:string;baseline:number;configured:number;next:number};
type Payload={requestId:string;code:string;customer:string;memo:string;amount:number|null};
const number=(code:string,seq:number)=>code+String(seq).padStart(6,"0");
const orderNumber=(o:Order)=>number(o.code,o.ordinal);
const PENDING="order-pending-v1";
async function api(path:string,method="GET",body?:unknown){const r=await fetch(path,{method,headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined,cache:"no-store"});const d=await r.json() as {error?:string;notIssued?:boolean;orders:Order[];order:Order;staff:Staff[];isAdmin:boolean};if(!r.ok){const e=new Error(d.error||"通信に失敗しました") as Error & {notIssued?:boolean};e.notIssued=d.notIssued;throw e;}return d;}
export default function Home(){
 const [staff,setStaff]=useState<Staff[]>([]),[code,setCode]=useState("411C"),[admin,setAdmin]=useState(false),[orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[q,setQ]=useState(""),[customer,setCustomer]=useState(""),[memo,setMemo]=useState(""),[amount,setAmount]=useState(""),[latest,setLatest]=useState<Order|null>(null),[cancel,setCancel]=useState<Order|null>(null),[pending,setPending]=useState(false);
 const [manage,setManage]=useState(false),[newName,setNewName]=useState(""),[newCode,setNewCode]=useState(""),[newNext,setNewNext]=useState("1"),[editCode,setEditCode]=useState("411C"),[editNext,setEditNext]=useState(""),[settingError,setSettingError]=useState(""),[staged,setStaged]=useState<{mode:"add"|"edit";code:string;next:number;name?:string}|null>(null);
 const lock=useRef(false),activeCode=useRef("411C");
 async function refresh(selected=activeCode.current){
  try{const [s,h]=await Promise.all([api("/api/staff"),api("/api/orders?code="+selected)]);setStaff(s.staff);setAdmin(s.isAdmin);if(selected===activeCode.current)setOrders(h.orders);setError("");}
  catch(e){setError((e as Error).message);}finally{setLoading(false);}
 }
 useEffect(()=>{
  try{const p=localStorage.getItem(PENDING);const saved=p?JSON.parse(p).code||"411C":localStorage.getItem("order-selected-staff");if(saved&&/^[0-9]{3}C$/.test(saved)){activeCode.current=saved;setCode(saved);setEditCode(saved);}setPending(!!p);}catch{}
  refresh();if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});
  const focus=()=>refresh();window.addEventListener("focus",focus);return()=>window.removeEventListener("focus",focus);
 },[]);
 function choose(value:string){if(busy||pending)return;activeCode.current=value;setCode(value);setEditCode(value);setOrders([]);setLatest(null);setQ("");setCustomer("");setMemo("");setAmount("");setLoading(true);try{localStorage.setItem("order-selected-staff",value);}catch{}refresh(value);}
 async function issue(){
  if(lock.current)return;lock.current=true;setBusy(true);setError("");
  try{
   let payload:Payload;const old=localStorage.getItem(PENDING);
   if(old){payload=JSON.parse(old);payload.code=payload.code||"411C";}
   else{const value=amount===""?null:Number(amount);if(value!==null&&(!Number.isSafeInteger(value)||value<0||value>999999999999))throw new Error("金額は0以上の整数で入力してください。");payload={requestId:crypto.randomUUID(),code:activeCode.current,customer,memo,amount:value};localStorage.setItem(PENDING,JSON.stringify(payload));setPending(true);}
   const d=await api("/api/orders","POST",payload);localStorage.removeItem(PENDING);setPending(false);setLatest(d.order);setOrders(prev=>[d.order,...prev.filter(x=>x.seq!==d.order.seq)]);setCustomer("");setMemo("");setAmount("");toast.success(orderNumber(d.order)+" を発行しました");await refresh();
  }catch(e){if((e as Error & {notIssued?:boolean}).notIssued){localStorage.removeItem(PENDING);setPending(false);}setError((e as Error).message);}finally{setBusy(false);lock.current=false;}
 }
 async function revoke(){if(!cancel||lock.current)return;lock.current=true;setBusy(true);try{const d=await api("/api/orders","PATCH",{seq:cancel.seq});setOrders(prev=>prev.map(x=>x.seq===d.order.seq?d.order:x));setLatest(prev=>prev?.seq===d.order.seq?null:prev);toast.success("取消しました。番号は再利用されません。");setError("");}catch(e){setError((e as Error).message);}finally{setCancel(null);setBusy(false);lock.current=false;}}
 async function copy(n:string){try{await navigator.clipboard.writeText(n);toast.success("番号をコピーしました");}catch{setError("コピーできませんでした。表示されている番号を長押ししてコピーしてください。");}}
 async function saveSetting(){
  if(!staged||lock.current)return;const value=staged;setStaged(null);lock.current=true;setBusy(true);setSettingError("");
  try{await api("/api/staff",value.mode==="add"?"POST":"PATCH",value.mode==="add"?{code:value.code,name:value.name,next:value.next}:{code:value.code,next:value.next});toast.success(value.mode==="add"?"担当者を追加しました":"次の番号を設定しました");setNewName("");setNewCode("");setNewNext("1");setEditNext("");await refresh();}
  catch(e){setSettingError((e as Error).message);}finally{setBusy(false);lock.current=false;}
 }
 function stage(mode:"add"|"edit"){
  const value=Number(mode==="add"?newNext:editNext),staffCode=mode==="add"?newCode.toUpperCase():editCode;
  if(!/^[0-9]{3}C$/.test(staffCode)||!Number.isInteger(value)||value<1||value>999999||(mode==="add"&&!newName.trim())){setSettingError("名前・担当コード（数字3桁＋C）・連番（1〜999999）を確認してください。");return;}
  setSettingError("");setStaged({mode,code:staffCode,next:value,name:newName.trim()});
 }
 useEffect(()=>{
  const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
  Promise.resolve(context.registerTool({name:"read_order_history",title:"発行履歴を確認",description:"指定した担当者の注文番号の履歴を取得する",inputSchema:{type:"object",properties:{code:{type:"string",pattern:"^[0-9]{3}C$"}},required:["code"],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:unknown)=>{const p=input as {code?:unknown};if(!p||typeof p.code!=="string"||!/^[0-9]{3}C$/.test(p.code)||Object.keys(p).length!==1)throw new Error("担当コードを確認してください");const d=await api("/api/orders?code="+p.code);if(p.code===activeCode.current)setOrders(d.orders);return {orders:d.orders};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();
 },[]);
 const current=staff.find(s=>s.code===code),editing=staff.find(s=>s.code===editCode),visible=orders.filter(o=>(orderNumber(o)+" "+o.customer+" "+o.memo).toLowerCase().includes(q.toLowerCase()));
 return <><Toaster position="top-center"/><header><div className="brand"><span className="mark"><Hash size={25}/></span><div><strong>注文番号発番</strong><small>担当者ごとの連番を共有</small></div></div>{admin?<button className="header-action" onClick={()=>{setManage(true);setSettingError("");}}><Settings size={18}/>担当者・番号設定</button>:<span className="badge">共有発番</span>}</header><main>
 <div className="notice"><b>運用前の確認</b>　印刷済みの用紙・会社に登録済みの番号と照合してください。未使用の紙を併用する場合は、印刷済みの最後の番号より後から始めてください。</div>
 {error&&<div role="alert" className="error">{error}<button className="secondary" style={{marginLeft:12}} onClick={()=>refresh()}>再読込</button></div>}
 <div className="workspace"><section className="panel"><div className="panel-body"><label className="staff-picker">発番する担当者<Select value={code} onValueChange={choose} disabled={busy||pending||loading}><SelectTrigger className="staff-select"><SelectValue placeholder="担当者を選択"/></SelectTrigger><SelectContent>{staff.map(s=><SelectItem key={s.code} value={s.code}>{s.name}　{s.code}</SelectItem>)}</SelectContent></Select></label>
 <div className="number-area"><div className="label">次の注文番号</div><div className="number">{loading?"読込中…":!current?"担当者を選択":current.next>999999?"上限に達しました":<><span>{code}</span>{String(current.next).padStart(6,"0")}</>}</div><p className="next-note">番号は発行時に確定します。他の端末で発行されると表示より進むことがあります。</p></div>
 {!loading&&current&&!current.configured&&<div className="setup-note">先に次の番号を設定してください。{admin&&<button className="secondary" onClick={()=>{setEditCode(code);setEditNext(String(current.next));setManage(true);}}>番号を設定</button>}</div>}
 <button className="primary" onClick={issue} disabled={busy||loading||(!pending&&(!current?.configured||current.next>999999))}>{busy?<RotateCw size={21}/>:<Plus size={23}/>} {busy?"確認しています…":pending?"前回の発番を確認・再試行":"注文番号を発行する"}</button>
 {pending&&<p className="form-note">前回の発番が確認できるまで担当者を切り替えず、同じボタンから再試行してください。</p>}
 {latest&&!latest.cancelled_at&&<div className="latest" role="status"><div className="label">発行しました</div><strong>{orderNumber(latest)}</strong><button className="secondary" onClick={()=>copy(orderNumber(latest))}><Copy size={16}/>番号をコピー</button></div>}
 <details className="optional"><summary>得意先・内容を添える（任意）</summary><div className="fields"><label>得意先<input maxLength={100} value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="例：○○設備" disabled={busy||pending}/></label><label>内容・メモ<textarea rows={2} maxLength={500} value={memo} onChange={e=>setMemo(e.target.value)} placeholder="例：給湯器 1台" disabled={busy||pending}/></label><label>金額（円）<input inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="未入力でも発行できます" disabled={busy||pending}/></label></div></details></div></section>
 <section className="panel"><div className="history-head"><h2>{current?.name||code}の発行履歴</h2><div className="stats"><span>発行<b>{orders.length}件</b></span><span>取消<b>{orders.filter(x=>x.cancelled_at).length}件</b></span></div><div className="search"><Search size={20} color="#61748a"/><input aria-label="履歴を検索" placeholder="番号・得意先・内容で検索" value={q} onChange={e=>setQ(e.target.value)}/><button className="secondary" aria-label="履歴を更新" onClick={()=>refresh()} disabled={busy}><RotateCw size={17}/></button></div></div><div className="rows">{loading?<div className="empty">履歴を読み込んでいます…</div>:visible.length?visible.map(o=><article key={o.seq} className={"row "+(o.cancelled_at?"cancelled":"")}><div className="row-top"><button className="copy-number" onClick={()=>copy(orderNumber(o))} aria-label={orderNumber(o)+"をコピー"}>{orderNumber(o)}<Copy size={15}/></button>{o.cancelled_at&&<span className="tag">取消</span>}</div><time>{new Date(o.created_at).toLocaleString("ja-JP",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"})}</time>{o.customer&&<p><b>{o.customer}</b></p>}{o.memo&&<p>{o.memo}</p>}<div className="row-footer"><span>{o.amount!==null?o.amount.toLocaleString("ja-JP")+" 円":""}</span>{!o.cancelled_at&&<button className="cancel" onClick={()=>setCancel(o)} disabled={busy}>この番号を取消</button>}</div></article>):<div className="empty"><ClipboardList size={34}/><b>{q?"一致する履歴がありません":"まだ発行履歴はありません"}</b><p style={{fontSize:14,marginTop:8}}>{q?"検索する文字を変えてください。":"番号を設定してから発行してください。"}</p></div>}</div></section></div>
 <div className="foot"><ShieldCheck size={20}/><span>すべての端末で同じ保存先を使います。同じ担当者で同時に発番しても番号は重複せず、取消した番号も再利用されません。発番にはインターネット接続が必要です。</span></div><p className="form-note">iPhoneではSafariの共有メニューから「ホーム画面に追加」で使えます。</p></main>
 <Dialog open={manage} onOpenChange={open=>{if(!busy)setManage(open)}}><DialogContent className="settings-dialog"><DialogHeader><DialogTitle>担当者・番号設定</DialogTitle><DialogDescription>開始する番号は、会社の記録と未使用の紙を確認してから設定してください。</DialogDescription></DialogHeader>{settingError&&<div className="error" role="alert">{settingError}</div>}<section><h3><Settings size={18}/>次の番号を設定</h3><label>担当者<Select value={editCode} onValueChange={v=>{setEditCode(v);setEditNext("");}} disabled={busy}><SelectTrigger className="staff-select"><SelectValue/></SelectTrigger><SelectContent>{staff.map(s=><SelectItem key={s.code} value={s.code}>{s.name}　{s.code}</SelectItem>)}</SelectContent></Select></label><p className="form-note">現在の次番号：{editing?number(editing.code,editing.next):"—"}</p><label>次に発行する連番（数字だけ）<input inputMode="numeric" value={editNext} onChange={e=>setEditNext(e.target.value)} placeholder="例：351" disabled={busy}/></label><p className="form-note">例：{editCode}000350まで使用 → 351を入力。発行済み・設定済みの番号へは戻せません。</p><button className="primary" onClick={()=>stage("edit")} disabled={busy||pending}>次の番号を設定する</button></section><section className="settings-section"><h3><Users size={18}/>担当者を追加</h3><div className="fields"><label>担当者名<input maxLength={60} value={newName} onChange={e=>setNewName(e.target.value)} placeholder="例：担当者の名前" disabled={busy}/></label><label>担当コード<input maxLength={4} value={newCode} onChange={e=>setNewCode(e.target.value.toUpperCase())} placeholder="例：421C" disabled={busy}/></label><label>次に発行する連番<input inputMode="numeric" value={newNext} onChange={e=>setNewNext(e.target.value)} disabled={busy}/></label><button className="primary" onClick={()=>stage("add")} disabled={busy}>担当者を追加する</button></div></section><div className="share-note"><b>別のスマホで使うには</b><p>担当者登録後、ChatGPTのSitesでこのアプリの「共有」を開き、利用する人を招待してください。同じリンクを開き、本人の担当コードを選んで使います。</p><a href="https://chatgpt.com/sites" target="_blank" rel="noreferrer">Sitesの共有設定を開く</a></div></DialogContent></Dialog>
 <AlertDialog open={!!staged} onOpenChange={open=>{if(!open)setStaged(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{staged?.mode==="add"?"担当者を追加しますか？":"次の番号を変更しますか？"}</AlertDialogTitle><AlertDialogDescription>{staged&&number(staged.code,staged.next)} から発行します。印刷済み用紙・会社の登録済み番号との重複がないことを確認してください。設定後は番号を前に戻せません。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>戻る</AlertDialogCancel><AlertDialogAction onClick={saveSetting}>確認して設定する</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={!!cancel} onOpenChange={open=>{if(!open)setCancel(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{cancel&&orderNumber(cancel)} を取消しますか？</AlertDialogTitle><AlertDialogDescription>履歴は残り、この番号は再利用されません。取消は元に戻せません。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>戻る</AlertDialogCancel><AlertDialogAction onClick={revoke}>取消する</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}
